## Put comments here that give an overall description of what your
## functions do

## These two functions, makeCacheMatrix and cacheSolve, are used to solve the
# inverse of a given matrix in a time- and computation-efficeint way. The
# calculation of inverse of the given matrix is stored in an environment other
# than local environment, and can be called upon without re-caculating each
# time if the matrix has not changed. 

## Write a short comment describing this function

# This function is setup so that it sets the matrix,
# get the matrix, set the inverse of the matrix, 
# get the inverse of matrix. The result of makeCacheMatrix is not the matrix.

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y){
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get, 
       setinverse = setinverse,
       getinverse = getinverse)
  
  
}


## Write a short comment describing this function
# This function calculates the inverse of a special matrix generated by 
# makeCacheMatrix. It first check if the inverse of the matrix is calulated.
# If so, it skips the calculation and gets the invers from cache. Otherwise,
# it calculates the inverse of the data (i.e. the matrix) and sets this 
# inverse matrix in cache via setinverse function

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  m <- x$getinverse()
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data,...)
  x$setinverse
  m
}